# Generated by Django 4.1.2 on 2022-11-19 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MoodleUsers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('grupo', models.CharField(max_length=255)),
                ('estatus', models.CharField(max_length=255)),
                ('external_id', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField()),
            ],
            options={
                'db_table': 'testeview',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ConsultaSQL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curso', models.CharField(choices=[('Educação Física', 'Educação Física'), ('Enfermagem', 'Enfermagem'), ('Farmácia', 'Farmácia'), ('Fisioterapia', 'Fisioterapia'), ('Medicina', 'Medicina'), ('Nutrição', 'Nutrição'), ('Odontologia', 'Odontologia'), ('Psicologia', 'Psicologia')], max_length=45)),
                ('disciplina', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
